// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJcg0G2NO8XDmvSAdFKWmxGkZIAtMYzA8',
    appId: '1:638098946474:web:669e48d8aa8d6427b253d3',
    messagingSenderId: '638098946474',
    projectId: 'flutter-auth-1f4da',
    authDomain: 'flutter-auth-1f4da.firebaseapp.com',
    databaseURL: 'https://flutter-auth-1f4da.firebaseio.com',
    storageBucket: 'flutter-auth-1f4da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmTmdC5csBRwIO0SK_NtU4IQ3RpVEz_I8',
    appId: '1:638098946474:android:b2658cb6f8020749b253d3',
    messagingSenderId: '638098946474',
    projectId: 'flutter-auth-1f4da',
    databaseURL: 'https://flutter-auth-1f4da.firebaseio.com',
    storageBucket: 'flutter-auth-1f4da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPSnOuKiOcK5gA5gfhTtXcxRo9BkMlK0k',
    appId: '1:638098946474:ios:cbebdd0399bb26b5b253d3',
    messagingSenderId: '638098946474',
    projectId: 'flutter-auth-1f4da',
    databaseURL: 'https://flutter-auth-1f4da.firebaseio.com',
    storageBucket: 'flutter-auth-1f4da.appspot.com',
    androidClientId: '638098946474-hj4reqfor0eeu2500l7iqnegentl2ue5.apps.googleusercontent.com',
    iosBundleId: 'com.example.eStorePr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPSnOuKiOcK5gA5gfhTtXcxRo9BkMlK0k',
    appId: '1:638098946474:ios:cbebdd0399bb26b5b253d3',
    messagingSenderId: '638098946474',
    projectId: 'flutter-auth-1f4da',
    databaseURL: 'https://flutter-auth-1f4da.firebaseio.com',
    storageBucket: 'flutter-auth-1f4da.appspot.com',
    androidClientId: '638098946474-hj4reqfor0eeu2500l7iqnegentl2ue5.apps.googleusercontent.com',
    iosBundleId: 'com.example.eStorePr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJcg0G2NO8XDmvSAdFKWmxGkZIAtMYzA8',
    appId: '1:638098946474:web:616cb0774c8a2857b253d3',
    messagingSenderId: '638098946474',
    projectId: 'flutter-auth-1f4da',
    authDomain: 'flutter-auth-1f4da.firebaseapp.com',
    databaseURL: 'https://flutter-auth-1f4da.firebaseio.com',
    storageBucket: 'flutter-auth-1f4da.appspot.com',
  );
}
